name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: acdasm on ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}, ${{ matrix.arch }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [x64, arm64]
        exclude:
        - os: windows-latest
          arch: arm64
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build 'acdasm'
        run: ./gradlew nativeCompile
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: acdasm-${{ matrix.os }}-${{ matrix.arch }}
          path: cli/build/native/nativeCompile/acdasm*
